<?php

/**
 * Implementation of hook_menu
 */
function weforum_f21_menu() {
  $items = array();

  $items['admin/config/weforum_f21'] = array(
    'title' => 'F21 configuration',
    'description' => 'F21 credentials',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('weforum_f21_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'weforum_f21.admin.inc',
  );
  return $items;
}

function weforum_f21_test() {
  $f21 = weforum_f21_connect();
  return(!empty($f21));
}

function weforum_f21_connect() {
  static $f21;
  if (empty($f21)) {
    $username = variable_get('weforum_f21_username');
    $password = variable_get('weforum_f21_password');
    $hostname = variable_get('weforum_f21_host');
    $f21 = mssql_connect($hostname, $username, $password);
    if (empty($f21)) {
      watchdog('weforum_f21', 'Failed connection to F21 on %ip', array('%ip' => $hostname), WATCHDOG_ERROR);
    }
    else {
      mssql_select_db('FORUM21', $f21);
    }
  }
  return $f21;
}

function weforum_f21_query($sql) {
  $t_rows = array();
  if ($result = mssql_query($sql, weforum_f21_connect())) {
    while ($row = mssql_fetch_array($result)) {
      $t_rows[] = $row;
    }
    mssql_free_result($result);
  }

  return $t_rows;
}

